# Generated by Django 6.0.2 on 2026-03-16 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('urn', models.CharField(blank=True, db_index=True, help_text='Unique Reference Number from the client sheet.', max_length=20, null=True)),
                ('name', models.CharField(db_index=True, help_text='Organization / School name.', max_length=255)),
                ('local_authority', models.CharField(db_index=True, help_text='Local Authority the organization belongs to.', max_length=255)),
                ('phase', models.CharField(choices=[('16_plus', '16 Plus'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('all_through', 'All Through'), ('nursery', 'Nursery'), ('not_applicable', 'Not Applicable')], db_index=True, default='not_applicable', max_length=20)),
                ('gender', models.CharField(choices=[('mixed', 'Mixed'), ('boys', 'Boys'), ('girls', 'Girls')], default='mixed', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for geo-distance filtering.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for geo-distance filtering.', max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name', 'local_authority'],
                'indexes': [models.Index(fields=['name', 'local_authority'], name='organizatio_name_bac91a_idx'), models.Index(fields=['postcode'], name='organizatio_postcod_6edbb8_idx'), models.Index(fields=['town'], name='organizatio_town_5e2401_idx'), models.Index(fields=['phase'], name='organizatio_phase_504123_idx'), models.Index(fields=['latitude', 'longitude'], name='organizatio_latitud_98feac_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'local_authority'), name='unique_organization_per_local_authority')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contact_person', models.CharField(help_text='Full name of the contact person.', max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('work_email', models.EmailField(db_index=True, help_text='Unique work email for this contact.', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(help_text='The organization this contact belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Organization Contact',
                'verbose_name_plural': 'Organization Contacts',
                'ordering': ['contact_person'],
                'indexes': [models.Index(fields=['work_email'], name='organizatio_work_em_14389b_idx'), models.Index(fields=['organization'], name='organizatio_organiz_7aa978_idx')],
            },
        ),
    ]
