# Generated by Django 6.0.2 on 2026-03-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='gender',
            field=models.CharField(choices=[('both', 'Both'), ('boys', 'Boys'), ('girls', 'Girls')], default='both', max_length=10),
        ),
    ]
