# Generated by Django 6.0.2 on 2026-03-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='gender',
            field=models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed'), ('not_applicable', 'Not Applicable')], default='mixed', max_length=30),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phase',
            field=models.CharField(choices=[('16_plus', '16 Plus'), ('all_through', 'All Through'), ('middle_deemed_primary', 'Middle Deemed Primary'), ('middle_deemed_secondary', 'Middle Deemed Secondary'), ('not_applicable', 'Not Applicable'), ('nursery', 'Nursery'), ('primary', 'Primary'), ('secondary', 'Secondary')], db_index=True, default='not_applicable', max_length=50),
        ),
    ]
