# Generated by Django 6.0.2 on 2026-03-15 05:28

import candidate.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateUploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('additional_info', models.JSONField(default=dict, help_text='Additional info sent to AI for all CVs in this batch. Example: {"experience": 2.0, "skills": ["math"], "job_role": ["math teacher"]}')),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total CVs in this batch.')),
                ('processed_count', models.PositiveIntegerField(default=0, help_text='CVs processed successfully.')),
                ('failed_count', models.PositiveIntegerField(default=0, help_text='CVs that failed processing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upload Batch',
                'verbose_name_plural': 'Upload Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Extracted from CV by AI. Null if not found.', max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('years_of_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)])),
                ('skills', models.JSONField(blank=True, default=list, help_text='Example: ["Math Teacher", "Physics", "SEND Support"]')),
                ('source', models.CharField(choices=[('local_upload', 'Local Upload'), ('crm', 'CRM'), ('previous_db', 'Previous DB')], db_index=True, default='local_upload', max_length=30)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available'), ('open_to_offers', 'Open to Offers')], db_index=True, default='not_available', max_length=20)),
                ('quality_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('manual', 'Manual Review')], db_index=True, default='pending', max_length=20)),
                ('profile_photo_url', models.URLField(blank=True, help_text='Profile photo URL extracted by AI from the CV. Null if not found.', max_length=1000, null=True)),
                ('job_titles', models.JSONField(blank=True, default=list, help_text='Example: ["Math Teacher", "Science Teacher", "English Teacher"]')),
                ('original_cv_file', models.FileField(blank=True, help_text="Candidate's original uploaded CV (PDF).", null=True, upload_to=candidate.models.candidate_cv_upload_path)),
                ('ai_processing_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='not_started', max_length=20)),
                ('ai_task_id', models.CharField(blank=True, db_index=True, help_text='Task ID returned by the AI service. Used for polling.', max_length=100, null=True)),
                ('ai_enhanced_cv_content', models.JSONField(blank=True, help_text='Full structured JSON output from AI.', null=True)),
                ('ai_enhanced_cv_file', models.FileField(blank=True, help_text='WeasyPrint-generated enhanced CV PDF.', null=True, upload_to=candidate.models.candidate_enhanced_cv_upload_path)),
                ('ai_failure_reason', models.TextField(blank=True, help_text='Stores error message if AI processing failed.', null=True)),
                ('ai_retry_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times AI processing was retried.')),
                ('email_subject', models.CharField(blank=True, max_length=500, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, help_text='The upload batch this candidate belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='candidate.candidateuploadbatch')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source'], name='candidate_c_source_934ed2_idx'), models.Index(fields=['availability_status'], name='candidate_c_availab_1c10a3_idx'), models.Index(fields=['quality_status'], name='candidate_c_quality_f3bc2a_idx'), models.Index(fields=['ai_processing_status'], name='candidate_c_ai_proc_ab168b_idx'), models.Index(fields=['ai_task_id'], name='candidate_c_ai_task_b152c2_idx')],
            },
        ),
    ]
