# Generated by Django 6.0.2 on 2026-03-15 06:29

import candidate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='profile_photo_url',
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Profile photo stored in MinIO. Extracted by AI or uploaded manually.', null=True, upload_to=candidate.models.candidate_profile_photo_upload_path),
        ),
    ]
