# Generated by Django 6.0.2 on 2026-03-17 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_remove_candidate_profile_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='rewrite_failure_reason',
            field=models.TextField(blank=True, help_text='Stores error message if AI rewrite failed.', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rewrite_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', help_text='Tracks the status of the AI rewrite request.', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rewrite_task_id',
            field=models.CharField(blank=True, db_index=True, help_text='Task ID for AI rewrite. Separate from the original ai_task_id.', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['rewrite_task_id'], name='candidate_c_rewrite_33055d_idx'),
        ),
    ]
