# Generated by Django 6.0.2 on 2026-03-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_candidate_rewrite_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Populated on demand when geo filtering is used.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Populated on demand when geo filtering is used.', max_digits=9, null=True),
        ),
    ]
