# Generated by Django 6.0.2 on 2026-03-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_candidate_latitude_candidate_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='contacts_emailed_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of contacts emailed for this candidate so far.'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, help_text='When candidate info was last sent to organization contacts.', null=True),
        ),
    ]
