"""
Django settings for edukai project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# ---------------------------
# Helper parsers for env vars
# ---------------------------
def env_bool(val, default=False):
    if val is None:
        return default
    return str(val).lower() in ("true", "1", "yes", "y", "on")


def env_int(val, default=0):
    try:
        return int(val)
    except (TypeError, ValueError):
        return default


def env_list(val, default=None, sep=","):
    if val is None or val == "":
        return default or []
    return [v.strip() for v in str(val).split(sep) if v.strip()]


# ---------------------------------------------------------------------------
# Core
# ---------------------------------------------------------------------------
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY environment variable is not set!")

DEBUG = env_bool(os.getenv("DEBUG"), default=False)   # ✅ default False in prod

ALLOWED_HOSTS = env_list(os.getenv("ALLOWED_HOSTS"), default=[])


# ---------------------------------------------------------------------------
# Applications
# ---------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',
    'storages',
    'django_celery_beat',
]

LOCAL_APPS = [
    "account",
    "organization",
    "candidate",
]

INSTALLED_APPS += THIRD_PARTY_APPS + LOCAL_APPS


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edukai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edukai.wsgi.application'


# ---------------------------------------------------------------------------
# Database — PostgreSQL in production, SQLite in dev
# ---------------------------------------------------------------------------
if os.getenv("DATABASE_URL"):
    import dj_database_url
    DATABASES = {
        "default": dj_database_url.parse(
            os.getenv("DATABASE_URL"),
            conn_max_age=60,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ---------------------------------------------------------------------------
# Password Validation
# ---------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------------------------
# Internationalisation
# ---------------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/London'
USE_I18N      = True
USE_TZ        = True

AUTH_USER_MODEL = os.getenv("AUTH_USER_MODEL", "account.User")


# ---------------------------------------------------------------------------
# Security
# ---------------------------------------------------------------------------
SECURE_SSL_REDIRECT         = env_bool(os.getenv("SECURE_SSL_REDIRECT"),       default=False)
SESSION_COOKIE_SECURE       = env_bool(os.getenv("SESSION_COOKIE_SECURE"),      default=False)
CSRF_COOKIE_SECURE          = env_bool(os.getenv("CSRF_COOKIE_SECURE"),         default=False)
SECURE_HSTS_SECONDS         = env_int(os.getenv("SECURE_HSTS_SECONDS"),         default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS"), default=False)
SECURE_HSTS_PRELOAD         = env_bool(os.getenv("SECURE_HSTS_PRELOAD"),        default=False)
SECURE_PROXY_SSL_HEADER     = ("HTTP_X_FORWARDED_PROTO", "https") if not DEBUG else None


# ---------------------------------------------------------------------------
# Cookie SameSite
# ---------------------------------------------------------------------------
SESSION_COOKIE_SAMESITE = os.getenv("SESSION_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SAMESITE    = os.getenv("CSRF_COOKIE_SAMESITE",    "Lax")


# ---------------------------------------------------------------------------
# CORS & CSRF
# ---------------------------------------------------------------------------
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = env_list(
    os.getenv("CORS_ALLOWED_ORIGINS"),
    default=["http://localhost:3000", "http://127.0.0.1:3000"],
)

CSRF_TRUSTED_ORIGINS = env_list(
    os.getenv("CSRF_TRUSTED_ORIGINS"),
    default=[],
)


# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'account.authentication.CookieJWTAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',

        
        # SessionAuthentication enforces CSRF on POST/PATCH/PUT/DELETE
        # which breaks cookie-based JWT auth in browsers
        
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    "EXCEPTION_HANDLER": "account.authentication.custom_exception_handler",
}


# ---------------------------------------------------------------------------
# Simple JWT
# ---------------------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(hours=env_int(os.getenv("SIMPLE_JWT_ACCESS_TOKEN_HOURS"), 1)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env_int(os.getenv("SIMPLE_JWT_REFRESH_TOKEN_DAYS"), 7)),
    'ROTATE_REFRESH_TOKENS':      env_bool(os.getenv("SIMPLE_JWT_ROTATE_REFRESH_TOKENS"),      True),
    'BLACKLIST_AFTER_ROTATION':   env_bool(os.getenv("SIMPLE_JWT_BLACKLIST_AFTER_ROTATION"),    True),
    "AUTH_HEADER_TYPES":          ("Bearer",),
    "USER_ID_FIELD":              "id",
    "USER_ID_CLAIM":              "user_id",
    "AUTH_COOKIE_ACCESS":         "access_token",
    "REFRESH_COOKIE_NAME":        "refresh_token",
    "REFRESH_COOKIE_PATH":        "/api/auth",
}


# ---------------------------------------------------------------------------
# API Docs (drf-spectacular)
# ---------------------------------------------------------------------------
SPECTACULAR_SETTINGS = {
    'TITLE':               os.getenv("SPECTACULAR_TITLE",       'EduKai APIs'),
    'DESCRIPTION':         os.getenv("SPECTACULAR_DESCRIPTION", 'API documentation for EduKai'),
    'VERSION':             os.getenv("SPECTACULAR_VERSION",     '1.0.0'),
    'SERVE_INCLUDE_SCHEMA': env_bool(os.getenv("SPECTACULAR_SERVE_INCLUDE_SCHEMA"), False),
}


# ---------------------------------------------------------------------------
# Redis Cache
# ---------------------------------------------------------------------------
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/1")
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


# ---------------------------------------------------------------------------
# App Settings
# ---------------------------------------------------------------------------
APP_NAME = os.getenv("APP_NAME", "EduKai")

PASSWORD_RESET_OTP_LENGTH             = env_int(os.getenv("PASSWORD_RESET_OTP_LENGTH"),             6)      
PASSWORD_RESET_OTP_TTL                = env_int(os.getenv("PASSWORD_RESET_OTP_TTL"),                600)    # 10min
PASSWORD_RESET_VERIFIED_TTL           = env_int(os.getenv("PASSWORD_RESET_VERIFIED_TTL"),           600)    # 10min
PASSWORD_RESET_RESEND_COOLDOWN        = env_int(os.getenv("PASSWORD_RESET_RESEND_COOLDOWN"),        60)     # 1min
PASSWORD_RESET_MAX_REQUESTS_PER_HOUR  = env_int(os.getenv("PASSWORD_RESET_MAX_REQUESTS_PER_HOUR"),  5)
PASSWORD_RESET_MAX_VERIFY_ATTEMPTS    = env_int(os.getenv("PASSWORD_RESET_MAX_VERIFY_ATTEMPTS"),    5)
PASSWORD_RESET_OTP_PEPPER             = os.getenv("PASSWORD_RESET_OTP_PEPPER", "change-this-in-production")


# ---------------------------------------------------------------------------
# Email
# ---------------------------------------------------------------------------
DEFAULT_FROM_EMAIL  = os.getenv("DEFAULT_FROM_EMAIL", "noreply@edukai.com")
EMAIL_BACKEND       = os.getenv("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST          = os.getenv("EMAIL_HOST", "")
EMAIL_PORT          = env_int(os.getenv("EMAIL_PORT"), 587)
EMAIL_USE_TLS       = env_bool(os.getenv("EMAIL_USE_TLS"), True)
EMAIL_HOST_USER     = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")


# ---------------------------------------------------------------------------
# Static Files
# ---------------------------------------------------------------------------
STATIC_URL  = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
# ✅ Only add STATICFILES_DIRS entry if the directory actually exists
_static_dir = BASE_DIR / "static"
STATICFILES_DIRS = [_static_dir] if _static_dir.exists() else []


# ===========================================================================
# MinIO / AWS S3 Storage
# Django 4.2+ uses STORAGES dict instead of DEFAULT_FILE_STORAGE string.
# ===========================================================================
USE_S3 = env_bool(os.getenv("USE_S3"), default=False)

if USE_S3:
    AWS_ACCESS_KEY_ID       = os.getenv("MINIO_ACCESS_KEY",   "minioadmin")
    AWS_SECRET_ACCESS_KEY   = os.getenv("MINIO_SECRET_KEY",   "minioadmin123")
    AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_BUCKET_NAME",  "edukai")
    AWS_S3_ENDPOINT_URL     = os.getenv("MINIO_ENDPOINT_URL", "http://127.0.0.1:9000")
    AWS_S3_REGION_NAME      = os.getenv("MINIO_REGION",       "us-east-1")

    AWS_S3_ADDRESSING_STYLE = "path"
    AWS_QUERYSTRING_AUTH    = False
    AWS_S3_FILE_OVERWRITE   = False
    AWS_DEFAULT_ACL         = None

    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}

    # ✅ Public URL uses the EXTERNAL MinIO URL (for browser access)
    MINIO_PUBLIC_URL        = os.getenv("MINIO_PUBLIC_URL", AWS_S3_ENDPOINT_URL)
    MINIO_INTERNAL_URL      = os.getenv("MINIO_INTERNAL_URL", AWS_S3_ENDPOINT_URL)
    PRESIGNED_URL_EXPIRE_SECONDS = int(os.getenv("PRESIGNED_URL_EXPIRE_SECONDS", 86400))

    STORAGES = {
        "default":     {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

    MEDIA_URL = f"{MINIO_PUBLIC_URL}/{AWS_STORAGE_BUCKET_NAME}/"

else:
    STORAGES = {
        "default":     {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
    MEDIA_URL  = os.getenv("MEDIA_URL",  "/media/")
    MEDIA_ROOT = Path(os.getenv("MEDIA_ROOT", str(BASE_DIR / "media")))


# ---------------------------------------------------------------------------
# Celery
# ---------------------------------------------------------------------------
CELERY_BROKER_URL        = os.getenv("CELERY_BROKER_URL", "redis://redis:6379/2")
CELERY_RESULT_BACKEND    = os.getenv("CELERY_RESULT_BACKEND","redis://redis:6379/2")
CELERY_ACCEPT_CONTENT    = ["json"]
CELERY_TASK_SERIALIZER   = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE          = TIME_ZONE

# ---------------------------------------------------------------------------
# AI Integration
# ---------------------------------------------------------------------------
AI_BASE_URL              = os.getenv("AI_BASE_URL", "http://ai:8080")
AI_POLL_INTERVAL_SECONDS = env_int(os.getenv("AI_POLL_INTERVAL_SECONDS"), 20)
AI_POLL_MAX_RETRIES      = env_int(os.getenv("AI_POLL_MAX_RETRIES"),      15)

# ---------------------------------------------------------------------------
# PDF Generation
# ---------------------------------------------------------------------------
CV_LOGO_PATH = os.getenv("CV_LOGO_PATH", str(BASE_DIR / "media" / "images" / "CV_logo.png"))


# ---------------------------------------------------------------------------
# Upload limits
# ---------------------------------------------------------------------------
DATA_UPLOAD_MAX_MEMORY_SIZE = 524288000   # 500MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000   # 500MB

# ---------------------------------------------------------------------------
# Celery Task Routing — separate queues per task type
# ---------------------------------------------------------------------------
CELERY_TASK_QUEUES = {
    "default": {},
    "polling": {},
    "pdf":     {},
}
CELERY_TASK_DEFAULT_QUEUE = "default"

CELERY_TASK_ROUTES = {
    "candidate.tasks.process_cv":    {"queue": "default"},
    "candidate.tasks.poll_ai_result": {"queue": "polling"},
    "candidate.tasks.generate_pdf":  {"queue": "pdf"},
}

CELERY_TASK_ANNOTATIONS = {
    "candidate.tasks.process_cv": {
        "rate_limit": "20/m",   # max 20 AI calls per minute
    },
    "candidate.tasks.generate_pdf": {
        "rate_limit": "10/m",   # WeasyPrint is heavy
    },
    "organization.tasks.geocode_organization": {
        "rate_limit": "30/m",   # ✅ max 30/min = 1 every 2s, well under Nominatim limit
    },
}

# ---------------------------------------------------------------------------
# Celery Beat — periodic batch sync
# ---------------------------------------------------------------------------
CELERY_BEAT_SCHEDULE = {
    "sync-batch-counts": {
        "task": "candidate.tasks.sync_batch_counts",
        "schedule": 300,  # every 5 minutes
    },
}


# ---------------------------------------------------------------------------
# SendGrid
# ---------------------------------------------------------------------------
SENDGRID_API_KEY        = os.getenv("SENDGRID_API_KEY", "")
SENDGRID_FROM_EMAIL     = os.getenv("SENDGRID_FROM_EMAIL", "")
SENDGRID_FROM_NAME      = os.getenv("SENDGRID_FROM_NAME", "Education Specialists Agency")
SENDGRID_REPLY_TO_EMAIL = os.getenv("SENDGRID_REPLY_TO_EMAIL", "")
SENDGRID_REPLY_TO_NAME  = os.getenv("SENDGRID_REPLY_TO_NAME", "")


# ---------------------------------------------------------------------------
# Pagination
# ---------------------------------------------------------------------------
REST_FRAMEWORK["DEFAULT_PAGINATION_CLASS"] = None  # we use manual pagination
PAGE_SIZE = 20


# ---------------------------------------------------------------------------
# Default primary key
# ---------------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'