# Generated by Django 6.0.2 on 2026-03-15 05:28

import account.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user (UUID4).', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text="User's country of residence.", max_length=100, null=True)),
                ('email', models.EmailField(db_index=True, help_text='Used as the login identifier.', max_length=254, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=account.models.user_profile_pic_path)),
                ('role', models.CharField(choices=[('superuser', 'Superuser'), ('normaluser', 'Normaluser')], db_index=True, default='normaluser', help_text='Defines user access level. Add new roles in choices.py.', max_length=30)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Deactivate instead of deleting accounts.')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['email'], name='account_use_email_553b8f_idx'), models.Index(fields=['role'], name='account_use_role_f4255b_idx')],
            },
        ),
    ]
