# Generated by Django 6.0.2 on 2026-03-17 16:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('batch_uploaded', 'Batch Uploaded'), ('batch_completed', 'Batch Completed'), ('batch_failed', 'Batch Failed'), ('cv_processed', 'CV Processed'), ('cv_failed', 'CV Failed'), ('emails_sent', 'Emails Sent'), ('cv_rewrite_completed', 'CV Rewrite Completed'), ('cv_rewrite_failed', 'CV Rewrite Failed'), ('org_import_completed', 'Org Import Completed'), ('contact_import_completed', 'Contact Import Completed')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], db_index=True, default='info', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('candidate_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('organization_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='account_act_event_t_e7421d_idx'), models.Index(fields=['severity', 'is_read'], name='account_act_severit_7e3687_idx')],
            },
        ),
    ]
